### ISSUE TITLE
Make  webstaging  for every pull request

### ISSUE THREAD

**Issue by oreyes1991** [rebelstackio/adventuretoursgroup#77]

**Comment by jegj** [comment]
@oreyes1991  @samo1811  will be helpful some documentation about the ticket  :smile: ....

**Comment by oreyes1991** [comment]
@jegj yes sorry, as @ReinsBrain told us we need a staging for pull requests, Production branch is master, but all pull request are made to develop branch those are the ones that nee to be reviewed by @cmexcel or @Lcup837 .

By now is fully static page see #75

**Comment by jegj** [comment]
@oreyes1991  @samo1811  That behavior is already done and fixed yesterday based on ticket https://github.com/rebelstackio/tepagopro/issues/23. To activate the deploy again for that pull request, please rebase the target branch with the lastest version of develop and push it with **-f**:

```sh
git rebase develop
git push origin <target_branch> -f
```
Tha should be enought to deploy a new site with the content on your staging site

Closing this issue. Please re-open it if that doesn't work

**Comment by jegj** [comment]
Sorry i was confused ... thought the ticket is related with the tepagopro repo that already have the pullrequest system. Going to add it to this repor

**Comment by jegj** [comment]
Closed by #82
